# Node.js with React
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'FrontlivetvDiplomat'
    appType: 'webApp'
    appName: 'diplomat3'
    deployToSlotOrASE: true
    resourceGroupName: 'diplomat3'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
